name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full clone for better Sonar analysis
          
      # Uncomment if you want to enforce Quality Gate to fail builds.
      # - name: Check SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Pull Blacklock Code Scanner Docker Image
        run: docker pull blacklocksec/code-scanner:latest

      - name: Run Blacklock Code Scanner
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/app" \
          -e SONAR_PROJECTKEY="nePz5gpnwhVUfHCa" \
          -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
          -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
          blacklocksec/code-scanner:latest
